ARG ELK_VERSION
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
COPY ./cacerts /usr/share/elasticsearch/jdk/lib/security/cacerts
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-nori