## docker build -t webflux-coroutine:0.0.1-SNAPSHOT .
FROM amazoncorretto:17.0.8

RUN mkdir /app
COPY ./build/libs/webflux-coroutine-0.0.1-SNAPSHOT.jar /app/app.jar

EXPOSE 8080
WORKDIR /app
ENTRYPOINT java -jar app.jar $ARGS