### Hello world
GET {{domain}}/
Content-Type: application/json

### create #1
POST {{domain}}/post
Content-Type: application/json

{
  "title"    : "test 1",
  "body"     : "demo 1",
  "authorId" : 1234
}

### create #2
POST {{domain}}/post
Content-Type: application/json

{
  "title"    : "test 2",
  "body"     : "demo 2",
  "authorId" : 1234
}

### create #3
POST {{domain}}/post
Content-Type: application/json

{
  "title"    : "test 3",
  "body"     : "demo 3",
  "authorId" : 1234
}

### create (error)
POST {{domain}}/post
Content-Type: application/json

{
  "title"    : "error",
  "body"     : "demo 3",
  "authorId" : 1234
}

### update
PUT {{domain}}/post/1
Content-Type: application/json

{
  "authorId" : 99369
}

### update (error)
PUT {{domain}}/post/-1
Content-Type: application/json

{
  "authorId" : 99369
}

### get all
GET {{domain}}/post/all
Content-Type: application/json

### get all by condition
GET {{domain}}/post/all?title=2
Content-Type: application/json

### get
GET {{domain}}/post/1
Content-Type: application/json

### get (error)
GET {{domain}}/post/-1
Content-Type: application/json

### delete
DELETE {{domain}}/post/2
Content-Type: application/json

##### Advanced cource

### test mdc
GET {{domain}}/test/mdc
Content-Type: application/json
#x-txid: merong

### test mdc (with trace)
GET {{domain}}/test/mdc?trace
Content-Type: application/json
#x-txid: merong

### external (hello)
GET {{domain}}/external/hello
Content-Type: application/json

### external (world)
GET {{domain}}/external/world
Content-Type: application/json

### cirbuit breaker
GET {{domain}}/circuit?fail=true&trace
Content-Type: application/json

### cirbuit breaker
GET http://localhost:8091/fail?fail=true&trace
Content-Type: application/json